### PR TITLE
Add vSphere clusters as Zabbix hosts objects in a hostgroup of your c…

### PR DESCRIPTION
**Pull request by alextoderita**
.yaml example:

 vsphere_object_clusters_as_zabbix_host:
    templates:
      - Template VMware vSphere Clusters - vPoller Native
    macros:
      VSPHERE.HOST: vcenter.internal
    groups:
      - Clusters

### CODE REVIEW

**Comment by dnaeon** [comment]
Thanks for your contribution!

Can you also please update the sample configuration file with the needed changes?

Thanks,
Marin

**Comment by dnaeon** [comment]
Also, please open another PR and yourself to the AUTHORS file.

**Comment by alextoderita** [comment]
Thanks Marin, it's done, I shall export the zabbix template for clusters
and send it to you, I remember you were creating a bundle with all those
templates.
How about the vpoller .rpm, are there any efforts regarding these?
Cheers!
Alex

**Comment by dnaeon** [comment]
Hey Alex,

If you already have an RPM spec file for building and packaging vPoller that would be great!

Please open another PR for this and I will merge it!

Thanks,
Marin

**Pull request merged**
