### PR TITLE
added regular expression filtering to vsphere VMs for zabbix import

### PR DESCRIPTION
**Pull request by pmelse**
The first of a few pull requests, this one requires no changes to yaml parsing.

More info in: https://github.com/dnaeon/py-vpoller/issues/199

### CODE REVIEW

**Comment by dnaeon** [comment]
Thanks for this pull request. 

I'd love to see this being actually configurable in the yaml document. That way you don't have to change the script, but the configuration used by it.

What do you think?

Thanks,
Marin

**Comment by pmelse** [comment]
Hi Marin,

That sounds like a great idea, can you have a look at my next pull request to see if I'm parsing new yaml keys sanely? #202 

I've got one more feature after that one, adding the first ipv4 address of each vm to the zabbix host's configuration IP settings (as determined by vm.guest.net.get ) (in hindsight, perhaps a flag for enabling / disabling this would be useful.)

**Comment by dnaeon** [comment]
Thanks, I'll check this one soon when I'm in front of my computer.

One thing that I've noticed though, is that you should use snake_case variables instead of CamelCase ones in your Python code.

I'll check the rest soon.

Thanks again!

**Comment by pmelse** [comment]
closing this request, updating with a new pull request in a few seconds.

**Pull request closed without merging**
